Repository Sprint-11-5-GlobalNomad/GlobalNomad, pull requests merged in 2025-02, with the labels that each got.

#104 Features/101 공통 로그인 유지 기능 구현
  src/app/api/auth-api.ts
  src/app/api/base-api.ts
  src/app/api/use-auth.ts
Labels: 📬 API, ⚙️ Setting

#111 Feat: 메인 페이지 검색 & 필터 & 페이지네이션 기능 및 CSS 구현
  next.config.ts
  package-lock.json
  package.json
  public/image/next-page-gray.svg
  public/image/next-page-green.svg
  public/image/previous-page-gray.svg
  public/image/previous-page-green.svg
  src/app/api/activities-api.ts
  src/app/page.tsx
  src/app/react-query/activity-state.ts
  src/app/react-query/use-infinite-scroll.ts
  src/app/types/activity-schemas.ts
  src/components/common/layout/indicator/error-indicator.tsx
  src/components/common/layout/indicator/loading-indicator.tsx
  src/components/common/ui/pagination.tsx
  src/components/pages/home/all-activities/all-activities-section.tsx
  src/components/pages/home/all-activities/all-activities-title.tsx
  src/components/pages/home/all-activities/all-activities.tsx
  src/components/pages/home/all-activities/category-price-filter.tsx
  src/components/pages/home/category-price-filter.tsx
  src/components/pages/home/hero-banner.tsx
  src/components/pages/home/popular-activities-title.tsx
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/components/pages/home/popular-activities/popular-activities-title.tsx
  src/components/pages/home/popular-activities/popular-activities.tsx
  src/components/pages/home/search/activity-explorer.tsx
  src/components/pages/home/search/search-form.tsx
  src/data/activity-data.ts
Labels: 📬 API, ✨ Feature, 🔨 Refactor, 🪮 Style

#113 Refactor: nav bar 로그인 상태 업데이트
  src/app/api/config/requestor.ts
  src/app/test/layout.tsx
  src/app/test/page.tsx
  src/components/common/layout/navigation/user-menu.tsx
  src/components/pages/home/popular-activities/popular-activities-title.tsx
  src/data/activity-data.ts
  src/stores/activity-store.tsx
  src/stores/notification-store.tsx
  src/stores/reservation-store.tsx
  src/stores/review-store.tsx
  src/stores/schedule-store.tsx
  src/stores/user-store.tsx
Labels: 📬 API, 🔨 Refactor

#122 feat: 리프레쉬 토큰 반복 재발급 현상 수정
  src/app/api/use-auth.ts
Labels: 🐞 BugFix

#124 fix: 리프레쉬 토큰 반복 재발급 현상 재수정
  src/app/api/base-api.ts
  src/app/api/use-auth.ts
Labels: 🐞 BugFix

#123 Refactor: 멘토링 피드백 반영 & 일부 오류 수정
  src/app/react-query/activity-state.ts
  src/app/types/activity-schemas.ts
  src/components/common/layout/navigation/user-menu.tsx
  src/components/common/layout/navigation/user-notifications.tsx
  src/components/pages/home/all-activities/all-activities-section.tsx
  src/components/pages/home/all-activities/category-price-filter.tsx
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/components/pages/home/search/activity-explorer.tsx
  src/utils/time-utils.ts
Labels: 🐞 BugFix, 🔨 Refactor

#126 Features/105 체험 등록수정 페이지 디자인 구현
  public/image/set_image_btn.svg
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-activities/post/page.tsx
  src/components/common/ui/dropdown/select-dropdown.tsx
Labels: ✨ Feature, 🪮 Style

#128 feat: 예약 내역 / 내 체험 페이지 디자인 수정
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-reservations/page.tsx
  src/components/common/layout/profile/my-page-card.tsx
Labels: ✨ Feature, 🪮 Style

#131 feat: useAuth훅 react query를 사용하여 관리
  src/app/api/use-auth.ts
Labels: ⚙️ Setting, 🔨 Refactor

#135 Fix: 네비게이션 바 UI 업데이트 지연 오류 해결 & Refactor: useAuth 훅 수정
  src/app/api/base-api.ts
  src/app/api/use-auth.ts
  src/app/login/page.tsx
  src/utils/remove-tokens.tsx
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor

#137 Features/136 내 체험 카드 수정삭제 로직 수정
  src/components/common/layout/profile/my-activity-card.tsx
  src/components/my-activity-card.tsx
Labels: ✨ Feature, 🔨 Refactor

#139 Feat: 체험 상세 제목(개요), 이미지 UI & API 연동 완료
  public/image/location.svg
  src/app/activity/[id]/page.tsx
  src/app/types/activity-schemas.ts
  src/components/common/layout/activity-detail/activity-images.tsx
  src/components/common/ui/dropdown/edit-delete-dropdown.tsx
  src/components/pages/activities-detail.tsx/activities-description.tsx
  src/components/pages/activity-detail/activity-info-header.tsx
Labels: 📬 API, ✨ Feature, 🪮 Style

#142 Feat: 체험 상세 default UI 구현 & API 연동작업(1)
  public/image/map-sample.svg
  src/app/activity/[id]/page.tsx
  src/app/api/activities-api.ts
  src/app/react-query/activity-state.ts
  src/app/types/activity-schemas.ts
  src/components/common/layout/activity-detail/activity-images.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/activity-info-header.tsx
  src/components/pages/activity-detail/booking-section.tsx
  src/components/pages/activity-detail/review-section.tsx
  src/components/pages/home/search/search-form.tsx
  src/utils/date-utils.ts
  tailwind.config.ts
Labels: 📬 API, ✨ Feature, 🔨 Refactor, 🪮 Style

#143 Features/106 체험 등록수정 페이지 기능 구현
  src/app/login/page.tsx
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-activities/post/_components/banner-image-uploader.tsx
  src/app/profile/my-activities/post/_components/intro-image-uploader.tsx
  src/app/profile/my-activities/post/_components/set-reservation-time.tsx
  src/app/profile/my-activities/post/_components/time-dropdown.tsx
  src/app/profile/my-activities/post/_constants/constants.ts
  src/app/profile/my-activities/post/page.tsx
  src/app/profile/my-reservations/component/review-modal.tsx
  src/app/profile/page.tsx
  src/app/signup/page.tsx
  src/app/types/button-type.ts
  src/components/common/ui/button.tsx
  src/components/pages/home/all-activities/category-price-filter.tsx
  src/components/pages/home/search/search-form.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
Labels: ✨ Feature

#145 Features/106 체험 등록수정 페이지 기능 구현
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/post/page.tsx
  src/components/common/ui/dropdown/select-dropdown.tsx
  src/components/pages/activity-post-edit/banner-image-uploader.tsx
  src/components/pages/activity-post-edit/intro-image-uploader.tsx
  src/components/pages/activity-post-edit/set-reservation-time.tsx
  src/components/pages/activity-post-edit/time-dropdown.tsx
Labels: 📬 API, ✨ Feature, 🪮 Style

#148 Hotfix: 로그인 기능 오류
  src/app/login/page.tsx
  src/hooks/use-login-mutation.ts
Labels: 🐞 BugFix

#146 Features/114 체험 상세 default UI
  package-lock.json
  package.json
  public/image/Add.svg
  public/image/Next.svg
  public/image/Prev.svg
  public/image/Subtract.svg
  src/components/common/ui/booking-calendar.tsx
  src/components/pages/activity-detail/booking-section.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: 📬 API, ✨ Feature, 🪮 Style

#149 Features/106 체험 등록수정 페이지 기능 구현
  package-lock.json
  package.json
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/post/page.tsx
  src/components/common/ui/dropdown/select-dropdown.tsx
  src/components/pages/activity-post-edit/date-selector.tsx
  src/components/pages/activity-post-edit/set-reservation-time.tsx
Labels: 📬 API, ✨ Feature, 🪮 Style

#151 Feat: 체험 상세 UI 완료 및 달력 API 연동 테스트 완료
  src/app/api/activities-api.ts
  src/app/login/page.tsx
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-reservations/page.tsx
  src/app/react-query/activity-state.ts
  src/app/types/activity-schemas.ts
  src/components/common/layout/profile/empty-activity.tsx
  src/components/common/layout/profile/empty-content.tsx
  src/components/common/ui/booking-calendar.tsx
  src/components/common/ui/pagination.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/activity-info-header.tsx
  src/components/pages/activity-detail/booking-section.tsx
  src/components/pages/home/all-activities/all-activities-section.tsx
  src/components/pages/home/hero-banner.tsx
  src/components/pages/home/search/activity-explorer.tsx
  src/components/pages/home/search/search-form.tsx
Labels: 📬 API, ✨ Feature, 🔨 Refactor, 🪮 Style

#155 feat: 카드 클릭 시 해당 체험 상세 페이지로 이동
  src/components/common/layout/profile/my-activity-card.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
Labels: 🔨 Refactor

#158 Feat: 체험 상세 예약 기능 완료
  src/app/react-query/activity-state.ts
  src/components/common/ui/booking-calendar.tsx
  src/components/common/ui/modal/message-modal.tsx
  src/components/pages/activity-detail/booking-section.tsx
Labels: 🐞 BugFix, 📬 API, ✨ Feature, 🔨 Refactor, 🪮 Style

#156 Features/153 필독 사항 필독 사항 구현
  package-lock.json
  package.json
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-activities/post/page.tsx
  src/app/profile/my-reservations/page.tsx
  src/app/react-query/use-infinite-scroll.ts
  src/components/common/layout/profile/my-activity-card.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
  src/hooks/use-can-delete-activity.ts
Labels: ✨ Feature, 🔨 Refactor

#170 Features/166 내 체험 등록 수정 이미지 url 변환 api 연결
  src/app/api/activities-api.ts
  src/app/api/my-activities-api.ts
  src/app/api/my-reservations-api.ts
  src/app/profile/my-activities/page.tsx
  src/app/react-query/activity-state.ts
  src/app/react-query/use-infinite-scroll.ts
  src/app/types/notification-schemas.ts
  src/components/pages/activity-post-edit/banner-image-uploader.tsx
  src/components/pages/activity-post-edit/intro-image-uploader.tsx
  src/hooks/use-can-delete-activity.ts
Labels: 🐞 BugFix, 📬 API, ✨ Feature, 🔨 Refactor

#172 Features/162 내 체험 등록 예약 가능 시간 드롭다운 옵션 높이 설정
  src/app/profile/my-activities/post/_constants/constants.ts
  src/components/pages/activity-detail/activity-info-header.tsx
  src/components/pages/activity-post-edit/set-reservation-time.tsx
  src/components/pages/activity-post-edit/time-dropdown.tsx
  src/styles/globals.css
Labels: 🔨 Refactor

#169 Feat: 카카오맵 연동 완료
  global.d.ts
  public/image/marker.png
  src/app/activity/[id]/page.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/activity-images.tsx
  src/components/pages/activity-detail/kakomaps/kakaomaps.tsx
  src/components/pages/activity-detail/kakomaps/markerInfo.tsx
Labels: 📬 API, ✨ Feature, 🪮 Style

#173 Features/161 내 체험 카드 삭제 모달 문구 수정 옵션 클릭 로직 수정
  src/components/common/layout/profile/my-activity-card.tsx
  src/components/common/ui/dropdown/edit-delete-dropdown.tsx
  src/components/common/ui/modal/confirmation-modal.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
Labels: 🔨 Refactor

#174 Feat: nav bar 리팩토링(알림 API, 무한 스크롤 등)
  src/app/api/my-notifications-api.ts
  src/app/react-query/use-infinite-scroll.ts
  src/components/common/layout/navigation/user-menu.tsx
  src/components/common/layout/navigation/user-notifications.tsx
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#176 Feat: 인기 체험 무한 스크롤 & 버튼 이동
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/components/pages/home/popular-activities/popular-activities.tsx
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#178 Features/175 체험 수정 예약 시간대 삭제 버그 수정
  package-lock.json
  src/app/api/use-auth.ts
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-activities/post/page.tsx
  src/app/profile/my-reservations/page.tsx
  src/components/pages/activity-post-edit/date-selector.tsx
  src/components/pages/activity-post-edit/set-reservation-time.tsx
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor

#182 Style: 메인 반응형 UI
  public/image/btn_arrow.svg
  public/image/right_arrow.svg
  src/app/react-query/use-infinite-scroll.ts
  src/app/signup/page.tsx
  src/components/common/ui/dropdown/filter-dropdown.tsx
  src/components/common/ui/pagination.tsx
  src/components/pages/home/all-activities/all-activities-section.tsx
  src/components/pages/home/all-activities/all-activities-title.tsx
  src/components/pages/home/all-activities/all-activities.tsx
  src/components/pages/home/all-activities/category-price-filter.tsx
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/styles/globals.css
Labels: 🔨 Refactor, 🪮 Style

#184 Features/181 공통 모달 이미지 삭제 버튼 투명도 설정
  src/app/profile/my-activities/[id]/edit/page.tsx
  src/app/profile/my-activities/post/page.tsx
  src/app/profile/my-reservations/component/review-modal.tsx
  src/components/common/ui/modal/confirmation-modal.tsx
  src/components/common/ui/modal/message-modal.tsx
  src/components/pages/activity-post-edit/banner-image-uploader.tsx
  src/components/pages/activity-post-edit/intro-image-uploader.tsx
Labels: 🪮 Style

#185 feat: 리프레쉬 토큰 로직 수정
  src/app/api/auth-api.ts
  src/app/api/base-api.ts
Labels: 🐞 BugFix, 📬 API

#187 feat: react-icon 삭제 후 svg 파일 생성
  package-lock.json
  package.json
  public/image/mini-calendar.svg
  src/components/pages/activity-post-edit/date-selector.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#193 feat: 리프레쉬 토큰 재발급 api 수정
  src/app/api/auth-api.ts
Labels: 📬 API, 🔨 Refactor

#194 feat: 로딩시 스켈레톤 적용(내 체험, 예약 내역 페이지)
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-reservations/page.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor, 🪮 Style

#196 feat: 이미지 파일 확장자 제한
  src/components/pages/activity-post-edit/banner-image-uploader.tsx
  src/components/pages/activity-post-edit/intro-image-uploader.tsx
Labels: 🔨 Refactor

#200 Feat & Style: 체험 상세 반응형 UI(태블릿)
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(primary)/activity/[id]/page.tsx
  src/app/(primary)/api/activities-api.ts
  src/app/(primary)/api/auth-api.ts
  src/app/(primary)/api/base-api.ts
  src/app/(primary)/api/my-activities-api.ts
  src/app/(primary)/api/my-notifications-api.ts
  src/app/(primary)/api/my-reservations-api.ts
  src/app/(primary)/api/use-auth.ts
  src/app/(primary)/api/user-api.ts
  src/app/(primary)/layout.tsx
  src/app/(primary)/page.tsx
  src/app/(primary)/profile/my-activities/[id]/edit/page.tsx
  src/app/(primary)/profile/my-activities/page.tsx
  src/app/(primary)/profile/my-activities/post/_constants/constants.ts
  src/app/(primary)/profile/my-activities/post/page.tsx
  src/app/(primary)/profile/my-activities/reservation/page.tsx
  src/app/(primary)/profile/my-reservations/page.tsx
  src/app/(primary)/profile/page.tsx
  src/app/profile/my-activities/reservation/reservation-modal.tsx
  src/app/react-query/activity-state.ts
  src/app/react-query/my-activity-state.ts
  src/app/react-query/notification-state.ts
  src/app/react-query/oauth-state.ts
  src/app/react-query/reservation-state.ts
  src/app/react-query/use-infinite-scroll.ts
  src/app/react-query/user-state.ts
  src/app/types/button-type.ts
  src/components/common/layout/navigation/user-menu.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/activity-images.tsx
  src/components/pages/activity-detail/activity-info-header.tsx
  src/components/pages/activity-detail/booking-modal.tsx
  src/components/pages/activity-detail/booking-section.tsx
  src/components/pages/activity-detail/kakomaps/kakaomaps.tsx
  src/components/pages/activity-detail/review-section.tsx
  src/components/pages/activity-post-edit/set-reservation-time.tsx
  src/components/pages/home/all-activities/all-activities-section.tsx
  src/components/pages/home/all-activities/all-activities.tsx
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
  src/components/pages/profile-reservation/review-modal.tsx
  src/utils/date-utils.ts
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor, 🪮 Style

#198 feat: 후기 작성 시 후기 작성 버튼 비활성화
  src/app/(primary)/profile/my-reservations/page.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
Labels: 🔨 Refactor

#208 Feat & Style: 체험 상세 모바일 UI 및 기능
  public/image/btn_pagination_arrow_left.svg
  public/image/btn_pagination_arrow_right.svg
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/common/ui/dropdown/edit-delete-dropdown.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/activity-images.tsx
  src/components/pages/activity-detail/activity-info-header.tsx
  src/components/pages/activity-detail/booking-section.tsx
  src/components/pages/activity-detail/kakomaps/kakaomaps.tsx
  src/components/pages/activity-detail/media-components/booking-modal.tsx
  src/components/pages/activity-detail/media-components/headcount-select-modal.tsx
  src/components/pages/activity-detail/review-section.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🔨 Refactor, 🪮 Style

#211 Feat: 반응형 카테고리 버튼 기능 구현
  src/components/pages/home/all-activities/category-price-filter.tsx
Labels: ✨ Feature, 🪮 Style

#205 feat: 재발급 api 테스트 완료
  src/app/(primary)/api/auth-api.ts
  src/app/(primary)/api/use-auth.ts
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor

#206 Features/199 usecandelete훅 리팩토링
  src/app/(primary)/api/my-activities-api.ts
  src/components/common/layout/profile/my-activity-card.tsx
  src/hooks/use-can-delete-activity.ts
Labels: 📬 API, 🔨 Refactor

#209 Features/207 공통 로딩 창을 스켈레톤으로 변경
  src/components/common/layout/navigation/user-notifications.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/activity-images.tsx
  src/components/pages/activity-detail/activity-info-header.tsx
  src/components/pages/activity-detail/review-section.tsx
  src/components/pages/home/all-activities/all-activites-skeleton-section.tsx
  src/components/pages/home/all-activities/all-activities-section.tsx
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/components/pages/home/search/activity-explorer.tsx
Labels: 🔨 Refactor, 🪮 Style

#215 fix: 리뷰 섹션 충돌 후 구조 문제 해결
  src/components/pages/activity-detail/review-section.tsx
  src/hooks/use-can-delete-activity.ts
Labels: 🐞 BugFix

#220 feat: 체험에 예약된 시간이 하나라도 있다면 해당 체험 수정이 불가능한 현상 수정
  src/app/(primary)/profile/my-activities/[id]/edit/page.tsx
  src/app/(primary)/profile/my-activities/post/page.tsx
  src/components/pages/activity-post-edit/set-reservation-time.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#224 feat: 버튼 컴포넌트 styled -> 테일윈드css로 변경
  src/app/types/button-type.ts
  src/components/common/ui/button.tsx
Labels: 🔨 Refactor, 🪮 Style

#231 feat: 버튼 컴포넌트 정적으로 수정
  src/app/types/button-type.ts
  src/components/common/ui/button.tsx
Labels: 🪮 Style

#232 Features/227 체험 등록 수정 멘토링 피드백 버그 수정
  src/app/(primary)/profile/my-activities/[id]/edit/page.tsx
  src/app/(primary)/profile/my-activities/post/page.tsx
  src/components/pages/activity-post-edit/banner-image-uploader.tsx
  src/components/pages/activity-post-edit/intro-image-uploader.tsx
  src/components/pages/activity-post-edit/set-reservation-time.tsx
  src/components/pages/activity-post-edit/time-dropdown.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#233 feat: 후기 작성 후 새로고침
  src/components/pages/profile-reservation/review-modal.tsx
Labels: 🔨 Refactor

#234 feat: 체험 카드 드롭다운 삭제하기 버튼 호버시 커서가 포인터가 되도록
  src/components/common/ui/dropdown/edit-delete-dropdown.tsx
Labels: 🪮 Style

#237 Feat: 메인 체험 상세 qa 피드백 반영
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(primary)/activity/[id]/page.tsx
  src/app/(primary)/api/base-api.ts
  src/app/react-query/notification-state.ts
  src/components/common/layout/navigation/user-menu.tsx
  src/components/common/layout/navigation/user-notifications.tsx
  src/components/common/ui/booking-calendar.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/activity-images.tsx
  src/components/pages/activity-detail/activity-info-header.tsx
  src/components/pages/activity-detail/booking-section.tsx
  src/components/pages/activity-detail/kakomaps/kakaomaps.tsx
  src/components/pages/activity-detail/media-components/booking-modal.tsx
  src/components/pages/activity-detail/review-section.tsx
  src/components/pages/home/all-activities/all-activites-skeleton-section.tsx
  src/components/pages/home/all-activities/all-activities.tsx
  src/components/pages/home/all-activities/category-price-filter.tsx
  src/components/pages/home/hero-banner.tsx
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/components/pages/home/search/activity-explorer.tsx
  src/components/pages/home/search/search-form.tsx
  tailwind.config.ts
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor, 🪮 Style

#238 feat: 하이드레이션 에러 해결 및 디바이스 별 갯수 맞도록 수정
  src/components/pages/home/all-activities/all-activites-skeleton-section.tsx
Labels: 🐞 BugFix

#239 Features/229 스켈레톤 수정
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/review-section.tsx
Labels: 🔨 Refactor

#244 Features/241 체험 등록 수정 추가 수정
  src/app/(primary)/profile/my-activities/[id]/edit/page.tsx
  src/app/(primary)/profile/my-activities/post/page.tsx
  src/components/common/layout/profile/my-activity-card.tsx
  src/components/common/ui/dropdown/edit-delete-dropdown.tsx
  src/components/common/ui/modal/message-modal.tsx
  src/components/pages/activity-post-edit/intro-image-uploader.tsx
  src/components/pages/activity-post-edit/set-reservation-time.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
Labels: 🔨 Refactor, 🪮 Style

#248 Fix: 메인 자체 qa 피드백 반영
  src/components/common/ui/pagination.tsx
  src/components/pages/home/all-activities/all-activities-section.tsx
  src/components/pages/home/all-activities/all-activities.tsx
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/components/pages/home/search/activity-explorer.tsx
Labels: 🐞 BugFix

#251 Features/247 공통 invalidate 작업 알아보기
  src/app/(primary)/profile/my-reservations/page.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
  src/components/pages/profile-reservation/review-modal.tsx
Labels: 🔨 Refactor

#252 Refacotr: 체험 상세 기능 CSS
  src/app/(primary)/activity/[id]/page.tsx
  src/app/react-query/activity-state.ts
  src/app/react-query/my-activity-state.ts
  src/app/react-query/notification-state.ts
  src/app/react-query/oauth-state.ts
  src/app/react-query/reservation-state.ts
  src/app/react-query/user-state.ts
  src/components/common/ui/pagination.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/activity-info-header.tsx
  src/components/pages/activity-detail/media-components/booking-modal.tsx
  src/components/pages/activity-detail/media-components/headcount-select-modal.tsx
  src/components/pages/activity-detail/review-section.tsx
Labels: 🐞 BugFix, 🔨 Refactor

#254 feat: 수정 페이지 주소 다시 추가
  src/app/(primary)/profile/my-activities/[id]/edit/page.tsx
  src/components/pages/activity-post-edit/kakao-map-address.tsx
Labels: 🔨 Refactor

#257 Fix & Style: 메인 체험 상세 모바일 디바이스 qa
  src/app/(auth)/login/page.tsx
  src/components/common/ui/booking-calendar.tsx
  src/components/common/ui/pagination.tsx
  src/components/pages/activity-detail/activity-details.tsx
  src/components/pages/activity-detail/kakomaps/kakaomaps.tsx
  src/components/pages/activity-detail/review-section.tsx
  src/components/pages/home/popular-activities/popular-activities-section.tsx
  src/components/pages/home/search/search-form.tsx
  tailwind.config.ts
Labels: 🐞 BugFix, 🪮 Style

#259 Fix: 후기 섹션 CSS & 페이지 기능 오류 해결
  src/components/common/layout/footer.tsx
  src/components/common/ui/pagination.tsx
  src/components/pages/activity-detail/review-section.tsx
Labels: 🐞 BugFix

#260 Features/258 qa 수정 체험 관리 후기 작성 체험 등록 수정페이지 설명글 제한 늘리기
  src/app/(primary)/api/use-auth.ts
  src/app/(primary)/profile/my-activities/[id]/edit/page.tsx
  src/app/(primary)/profile/my-activities/page.tsx
  src/app/(primary)/profile/my-activities/post/page.tsx
  src/app/(primary)/profile/my-reservations/page.tsx
  src/app/react-query/activity-state.ts
  src/app/react-query/my-activity-state.ts
  src/app/react-query/oauth-state.ts
  src/components/pages/activity-post-edit/time-dropdown.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
  src/components/pages/profile-reservation/review-modal.tsx
Labels: 🔨 Refactor, 🪮 Style
