Repository Sprint-11-5-GlobalNomad/GlobalNomad, pull requests merged in 2025-01, with the labels that each got.

#10 Features/8 기초 세팅 zustand 세팅
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/apis/activities-api.ts
  src/apis/apis.tsx
  src/apis/config/requestor.ts
  src/app/favicon.ico
  src/app/globals.css
  src/stores/activity-store.tsx
  src/stores/notification-store.tsx
  src/stores/reservation-store.tsx
  src/stores/review-store.tsx
  src/stores/schedule-store.tsx
  src/stores/types/activity-schemas.ts
  src/stores/types/notification-schemas.ts
  src/stores/types/oauth-schemas.ts
  src/stores/types/reservation-schemas.ts
  src/stores/types/review-schemas.ts
  src/stores/types/schedule-schemas.ts
  src/stores/types/user-schemas.ts
  src/stores/user-store.tsx
  src/types/activities-type.ts
  tsconfig.json
Labels: ⚙️ Setting, ✨ Feature

#26 fix: 중복 코드 / 쉼표 없음 해결
  package-lock.json
  tsconfig.json
Labels: 🐞 BugFix

#23 Feat&Refactor: font weight 변수화 및 font size 단위 통일
  tailwind.config.ts
Labels: 🔨 Refactor, 🪮 Style

#21 Features/11 공통 버튼 컴포넌트 생성
  .gitignore
  package.json
  src/components/button.tsx
  src/types/button-type.ts
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Feature

#28 Feat: Nav Bar default UI 완성
  .prettierrc
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/image/logo-big.svg
  public/image/logo-lg.svg
  public/image/logo-md.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/apis/apis.tsx
  src/app/api/activity/route.ts
  src/app/api/api.ts
  src/app/api/config/requestor.ts
  src/app/apis/activities-api.ts
  src/app/apis/config/requestor.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/navbar.tsx
  src/styles/globals.css
  tailwind.config.ts
Labels: ✨ Feature, 🪮 Style

#27 Feat: 수정하기/삭제하기 드롭다운
  src/app/card-drop-down-basic.tsx
  src/app/card-drop-down.tsx
  src/app/drop-down-basic.tsx
  src/app/more-menu.tsx
  src/app/test/layout.tsx
  src/app/test/page.tsx
Labels: ✨ Feature, 🪮 Style

#32 Features/31 공통 emptyactivity 컴포넌트 구현
  src/components/empty-activity.tsx
  tailwind.config.ts
Labels: ✨ Feature

#30 Features/24 공통 체험 카드 컴포넌트
  package-lock.json
  public/image/rating-star.svg
  src/components/my-activity-card.tsx
  src/components/my-reservation-card.tsx
  src/stores/types/reservation-schemas.ts
  tailwind.config.ts
Labels: ✨ Feature

#39 Feat: 로그인했을 때의 네비게이션 바 ui
  .vscode/settings.json
  public/image/notification.svg
  public/image/profile_default.svg
  src/app/layout.tsx
  src/app/test/page.tsx
  src/components/common/layout/footer.tsx
  src/components/common/layout/navbar.tsx
  src/components/common/layout/navigation/user-menu.tsx
  src/components/common/layout/navigation/user-notifications.tsx
  src/components/common/ui/button.tsx
  src/components/common/ui/card-drop-down-basic.tsx
  src/components/common/ui/card-drop-down.tsx
  src/components/common/ui/drop-down-basic.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🪮 Style

#34 Features/33 예약 내역 예약 내역 페이지 기본 구조 구현
  package-lock.json
  src/app/profile/reservation/page.tsx
Labels: ✨ Feature

#48 Features/38 예약 내역 후기작성 모달 컴포넌트 구현
  package-lock.json
  public/image/btn_X.svg
  public/image/rating-empty-star.svg
  public/image/rating-star.svg
  src/app/profile/reservation/component/review-modal.tsx
  src/components/common/ui/button.tsx
  src/stores/types/review-schemas.ts
Labels: 📬 API, ✨ Feature

#41 Refactor: dropdown ui & 상태 관리 추가
  src/app/more-menu.tsx
  src/app/test/page.tsx
  src/components/common/layout/navigation/user-notifications.tsx
  src/components/common/ui/card-drop-down.tsx
  src/components/common/ui/category-dropdown.tsx
  src/components/common/ui/drop-down-basic.tsx
  src/components/common/ui/edit-delete-dropdown.tsx
  src/components/common/ui/filter-dropdown.tsx
Labels: ✨ Feature, 🔨 Refactor, 🪮 Style

#45 Feat: 필터 드롭다운(정렬, 필터) & Refactor: 모든 드롭다운 세부 CSS 수정
  package-lock.json
  package.json
  public/image/green-arrow-down.svg
  public/image/meatball.svg
  src/app/api/activity/route.ts
  src/app/test/page.tsx
  src/components/common/icons/dropdown-arrow-icon.tsx
  src/components/common/icons/dropdown-check-icon.tsx
  src/components/common/ui/edit-delete-dropdown.tsx
  src/components/common/ui/filter-dropdown.tsx
  src/components/common/ui/select-dropdown.tsx
Labels: ✨ Feature, 🔨 Refactor, 🪮 Style

#55 Feat: Footer
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/profile/activity/page.tsx
  src/app/signup/page.tsx
  src/components/common/layout/footer.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🪮 Style

#63 Features/49 기초세팅 전역 상태 관리 react query 세팅
  package-lock.json
  package.json
  src/app/api/activities-api.ts
  src/app/api/auth-api.ts
  src/app/api/base-api.ts
  src/app/api/my-activities-api.ts
  src/app/api/my-notifications-api.ts
  src/app/api/my-reservations-api.ts
  src/app/api/user-api.ts
  src/app/layout.tsx
  src/app/profile/reservation/page.tsx
  src/app/react-query/activity-state.ts
  src/app/react-query/my-activity-state.ts
  src/app/react-query/notification-state.ts
  src/app/react-query/oauth-state.ts
  src/app/react-query/react-query-util.ts
  src/app/react-query/react-query.ts
  src/app/react-query/reservation-state.ts
  src/app/react-query/user-state.ts
  src/app/types/activities-type.ts
  src/app/types/activity-schemas.ts
  src/app/types/notification-schemas.ts
  src/app/types/oauth-schemas.ts
  src/app/types/reservation-schemas.ts
  src/app/types/review-schemas.ts
  src/app/types/schedule-schemas.ts
  src/app/types/user-schemas.ts
  src/components/my-activity-card.tsx
  src/components/my-reservation-card.tsx
  src/stores/activity-store.tsx
  src/stores/notification-store.tsx
  src/stores/reservation-store.tsx
  src/stores/review-store.tsx
  src/stores/schedule-store.tsx
  src/stores/user-store.tsx
  tsconfig.json
Labels: 📬 API, ⚙️ Setting, ✨ Feature

#65 Features/64 공통 체험 예약 카드 컴포넌트 리팩토링
  package-lock.json
  package.json
  src/app/profile/reservation/component/review-modal.tsx
  src/components/common/ui/button.tsx
  src/components/common/ui/edit-delete-dropdown.tsx
  src/components/my-activity-card.tsx
  src/components/my-reservation-card.tsx
  src/types/button-type.ts
Labels: ✨ Feature, 🔨 Refactor

#68 Fix: layout.tsx에서 서버-클라이언트 컴포넌트 충돌 해결 & useCustomQuery 인자 이슈 해결
  src/app/layout.tsx
  src/app/react-query/query-provider.tsx
  src/app/react-query/react-query-util.ts
Labels: 🐞 BugFix

#71 Feat: Nav Bar 알림 기본 UI 구현
  .env.local
  package-lock.json
  package.json
  public/image/btn_X.svg
  public/image/btn_X_gray_medium.svg
  src/app/react-query/notification-state.ts
  src/components/common/icons/close-button.tsx
  src/components/common/layout/navigation/user-notifications.tsx
  src/types/activities-type.ts
  src/types/button-type.ts
  src/utils/higlight-text.tsx
  src/utils/time-utils.ts
  tailwind.config.ts
Labels: ✨ Feature, 🪮 Style

#74 Remove .env.local from version control
  .env.local
Labels: 🐞 BugFix

#72 Features/66 예약 내역 페이지 구현
  src/app/api/my-reservations-api.ts
  src/app/profile/reservation/component/review-modal.tsx
  src/app/profile/reservation/page.tsx
  src/app/react-query/reservation-state.ts
  src/app/types/button-type.ts
  src/components/common/ui/button.tsx
  src/components/common/ui/filter-dropdown.tsx
  src/components/confirmation-modal.tsx
  src/components/my-reservation-card.tsx
Labels: ✨ Feature, 🔨 Refactor, 🪮 Style

#76 Style: 알림 반응형 CSS 구현
  src/app/layout.tsx
  src/app/react-query/notification-state.ts
  src/components/common/icons/close-button.tsx
  src/components/common/layout/navigation/user-notifications.tsx
Labels: 🔨 Refactor, 🪮 Style

#79 Style: Nav Bar 상단 고정 & 메인 기본 ui 틀
  public/image/activated_left_arrow.svg
  public/image/activated_right_arrow.svg
  public/image/main_banner.jpg
  public/image/search.svg
  public/image/unactivated_left_arrow.svg
  public/image/unactivated_right_arrow.svg
  src/app/page.tsx
  src/components/common/layout/navbar.tsx
  src/components/common/ui/card-drop-down-basic.tsx
  src/components/common/ui/category-dropdown.tsx
  src/components/common/ui/select-dropdown.tsx
Labels: 🪮 Style

#61 Features/44 로그인 페이지
  .gitattributes
  package-lock.json
  package.json
  public/image/Google-Icon.svg
  public/image/Kakao-Icon.svg
  public/image/visibility_eye.svg
  public/image/visibility_off.svg
  public/logo.svg
  src/app/login/page.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🪮 Style

#70 feat:회원가입 페이지 default UI 완성
  src/app/signup/page.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🪮 Style

#83 Features/78 공통 react query 구조 최적화
  src/app/react-query/activity-state.ts
  src/app/react-query/my-activity-state.ts
  src/app/react-query/notification-state.ts
  src/app/react-query/oauth-state.ts
  src/app/react-query/react-query-util.ts
  src/app/react-query/reservation-state.ts
  src/app/react-query/user-state.ts
Labels: 📬 API, ⚙️ Setting, 🔨 Refactor

#85 feat: 버튼 컴포넌트 리팩토링
  src/app/page.tsx
  src/app/types/button-type.ts
  src/components/common/ui/button.tsx
Labels: ✨ Feature, 🔨 Refactor

#86 feat: 400에러 메시지 수정
  src/app/react-query/activity-state.ts
  src/app/react-query/my-activity-state.ts
  src/app/react-query/notification-state.ts
  src/app/react-query/oauth-state.ts
  src/app/react-query/reservation-state.ts
  src/app/react-query/user-state.ts
Labels: 🔨 Refactor

#87 Style: 메인 기본 ui
  public/image/next-page.svg
  public/image/previous-page.svg
  src/app/page.tsx
  src/app/types/button-type.ts
  src/components/common/layout/navbar.tsx
  src/components/common/pages/experience-detail.tsx/experience-description.tsx
  src/components/common/pages/home/all-experiences-title.tsx
  src/components/common/pages/home/all-experiences.tsx
  src/components/common/pages/home/category-price-filter.tsx
  src/components/common/pages/home/hero-banner.tsx
  src/components/common/pages/home/popular-experiences-title.tsx
  src/components/common/pages/home/popular-experiences.tsx
  src/components/common/pages/home/search-section.tsx
  src/components/common/ui/button.tsx
  src/components/common/ui/pagination.tsx
  src/data/activity-data.ts
  src/styles/globals.css
  tailwind.config.ts
Labels: 🪮 Style

#90 Rename & Move: 컴포넌트 폴더 정리
  src/app/page.tsx
  src/app/profile/page.tsx
  src/app/profile/reservation/page.tsx
  src/app/test/page.tsx
  src/components/common/layout/profile/empty-activity.tsx
  src/components/common/layout/profile/my-activity-card.tsx
  src/components/common/layout/profile/my-page-card.tsx
  src/components/common/ui/dropdown/edit-delete-dropdown.tsx
  src/components/common/ui/dropdown/filter-dropdown.tsx
  src/components/common/ui/dropdown/select-dropdown.tsx
  src/components/common/ui/modal/confirmation-modal.tsx
  src/components/common/ui/modal/message-modal.tsx
  src/components/pages/activities-detail.tsx/activities-description.tsx
  src/components/pages/home/all-activities-title.tsx
  src/components/pages/home/all-activities.tsx
  src/components/pages/home/category-price-filter.tsx
  src/components/pages/home/hero-banner.tsx
  src/components/pages/home/popular-activities-title.tsx
  src/components/pages/home/popular-activities.tsx
  src/components/pages/home/search-section.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
Labels: 🔨 Refactor

#89 feat: 페이지네이션 선택 버전 추가
  src/components/common/ui/button.tsx
Labels: 🔨 Refactor

#93 feat: 내 체험 관리 페이지 디자인 구현 완료
  src/app/profile/activity/page.tsx
  src/app/profile/my-activities/page.tsx
Labels: ✨ Feature

#97 Features/92 내 체험 관리 페이지 구현
  src/app/react-query/activity-state.ts
  src/app/react-query/my-activity-state.ts
  src/app/react-query/notification-state.ts
  src/app/react-query/oauth-state.ts
  src/app/react-query/reservation-state.ts
  src/app/react-query/user-state.ts
  src/components/common/layout/profile/my-activity-card.tsx
Labels: 📬 API, ✨ Feature, 🔨 Refactor

#100 Features/98 내 체험 관리 기능 및 디자인 테스트
  src/app/api/activity/route.ts
  src/app/profile/my-activities/page.tsx
  src/app/profile/my-reservations/component/review-modal.tsx
  src/app/profile/my-reservations/page.tsx
  src/app/profile/page.tsx
  src/app/signup/page.tsx
  src/components/common/layout/profile/my-activity-card.tsx
  src/components/common/layout/profile/my-page-card.tsx
  src/components/pages/profile-reservation/my-reservation-card.tsx
Labels: ✨ Feature, 🔨 Refactor
